### ISSUE TITLE
Cannot add image when using absolute paths on Windows

### ISSUE THREAD

**Issue by Sirove** [nicfit/eyeD3#219]
It works fine if I open the command prompt inside the folder with the picture and mp3 file:

`eyeD3 --add-image "Test.jpg":FRONT_COVER "Test.mp3"`

But when using an ansolute path to the image it doesn't work:
```
eyeD3--add-image "C:\Users\Admin\Desktop\Test\Test.jpg":FRONT_COVER "C:\Users\Admin\Desktop\Test\Test.mp3"
eyeD3: error: argument --add-image: invalid pic type: \Syncthing\Podcasts\HiddenBrain\Hidden Brain.jpg
```

**Comment by nicfit** [comment]
I don't have Windows, but it seems like maybe ':' special. FRONT_COVER is meant to be the "picture type", not sure why the command line parsing is different.

**Comment by Sirove** [comment]
I also tried using environment variables like `%UserProfile%\Desktop\Test\Test.jpg` but still the same error...

**Comment by chamatht** [comment]
This issue is unique to windows.
The issue can be resolved by **adding a single**  ``\ ``  **after the drive letter.**
 -  ``eyeD3 --add-image C\:\Users\Admin\Desktop\Test\Test.jpg:FRONT_COVER C:\Users\Admin\Desktop\Test\Test.mp3``

if you're using a url then **add a single** `` \`` **after http.**
 - ``eyeD3 --add-image http\://www.examaple.com/Test.jpg:FRONT_COVER C:\Users\Admin\Desktop\Test\Test.mp3``

### more info
After some testing and debugging, I found out that python argparser in windows doubles the number of ``\``. This happens only on windows.

On eyedD3 docs, it's mentioned how to avoid this issue with ``\\``.  It only works with macOS and linux. For windows adding one ``\`` is enough, because argparser doubles it.
May be it's a good idea to mention this in the docs for windows users.

**Comment by Sirove** [comment]
It works! Thanks!

**Comment by elcoso** [comment]
2020- still broken and the example you give is only for url images not local. If I use "C\\:" the path is wrong and doesnt work.

**Comment by fitzzz** [comment]
> This issue is unique to windows. The issue can be resolved by **adding a single** `\ ` **after the drive letter.**
> 
> * `eyeD3 --add-image C\:\Users\Admin\Desktop\Test\Test.jpg:FRONT_COVER C:\Users\Admin\Desktop\Test\Test.mp3`
> 
> if you're using a url then **add a single** ` \` **after http.**
> 
> * `eyeD3 --add-image http\://www.examaple.com/Test.jpg:FRONT_COVER C:\Users\Admin\Desktop\Test\Test.mp3`
> 
> ### more info
> After some testing and debugging, I found out that python argparser in windows doubles the number of `\`. This happens only on windows.
> 
> On eyedD3 docs, it's mentioned how to avoid this issue with `\\`. It only works with macOS and linux. For windows adding one `\` is enough, because argparser doubles it. May be it's a good idea to mention this in the docs for windows users.

It was weird to add a C\:\ but hey, it worked on local files!  Thanks!  

FYI: I also had to remove all / and replace them with \.
