### ISSUE TITLE
Cant get image from tag.images object

### ISSUE THREAD

**Issue by willkara** [nicfit/eyeD3#260]
Now, I may be doing this wrong as I just started using the library.

I'm currently debugging it like this:

        print(tags.images.get(FRONT_COVER))

It's currently printing out **None**, so that leads me to believe that I'm accessing the images incorrectly. Are there any docs on how to GET the images? I've found a few on SETTING them, but not GETTING them.

**Comment by nicfit** [comment]
And what images are in the tag?

**Comment by fcastilloec** [comment]
@willkara I'm assuming that you declared `FRONT_COVER = eyed3.id3.frames.ImageFrame.FRONT_COVER` in your script.

I'm not sure how to retrieve a particular type of image, but you could do this:

```python
IMAGES = audiofile.tag.images

for IMAGE in IMAGES:
  if IMAGE.picture_type == FRONT_COVER:
    IMAGE.image_data #This contains the actual binary image data
    # Some code where IMAGE is a eyed3.id3.frames.ImageFrame
```
You can read more about [ImageFrame](https://eyed3.readthedocs.io/en/latest/eyed3.id3.html?highlight=images#eyed3.id3.frames.ImageFrame)

~~The main problem with this code is that the APIC field where the images are usually stored can exist on a file without containing any image data. In this case, eyeD3 will throw a `WARNING:eyed3.core:APIC frame does not contain image data/url`, which I've been trying to figure out how to test for.~~
~~This warning will show as soon as you run `eyed3.load`, and with my limited python knowledge, I have no idea how to catch it. It seems that's just a stdout message rather than an actual warning, but again, my python knowledge is extremely basic.~~

~~If @willkara or @nicfit know of a way to catch that warning, I would be forever thankful!~~

EDIT:
The actual image data is in `IMAGE.image_data`, and to solve my problem, I'm just testing that this is not zero.

**Comment by willkara** [comment]
Haven't had time for this project recently but I'll try to experiment a bit
when I get a chance!
