### ISSUE TITLE
Writing lyrics deletes TSOP tag (ARTISTSORT)

### ISSUE THREAD

**Issue by Wasnix** [nicfit/eyeD3#76]
A strange side effect of writing lyrics is that TSOP tags are deleted. 

I'm using these artist tags (TPE1, TPE2, TSOP, TSO2). TSOP disappeares after writing lyrics tag.

I'm using latest Debian Linux (buster) with eyeD3 version 0.8-1

**Comment by nicfit** [comment]
I'm guessing that a conversion to ID2.3 is happening? Is so, since TSOP is only valid in 2.4 it is converted to its 2.3 fram XSOP. It converted to 2.4  XSOP becomes TSOP again.

The following scripts helps show this:
```bash
#!/usr/bin/env bash
set -x

rm issue76.id3
touch issue76.id3

eyeD3 --to-v2.4 --text-frame 'TPE1:This is TPE1' \
      --text-frame 'TPE2:This is TPE2' --text-frame 'TSOP:This is TSOP' \
       --text-frame 'TSO2:This is TSO2' issue76.id3
eyeD3 issue76.id3 --verbose | grep 'TPE\|SO'
eyeD3 issue76.id3 --add-lyrics lyrics.txt
eyeD3 issue76.id3 --verbose | grep 'TPE\|SO'

eyeD3 issue76.id3 --to-v2.3
eyeD3 issue76.id3 --verbose | grep 'TPE\|SO'

eyeD3 issue76.id3 --to-v2.4
eyeD3 issue76.id3 --verbose | grep 'TPE\|SO'
```

I'm keeping this open as a reminder to turn the script into a pytest to ensure these conversions don't break.
